#!/usr/bin/python

import rospy
from recovery_supervisor_msgs.msg import Demo
from nav_msgs.msg import Path

class DemoViz:

    def __init__(self):
        rospy.init_node('demo_viz', anonymous = True)
        self.demo_sub = rospy.Subscriber('/recovery_supervisor/demo', Demo, self.callback)

        self.odom_path_pub = rospy.Publisher('odom_path', Path, queue_size=10, latch=True)
        self.demo_path_pub = rospy.Publisher('demo_path', Path, queue_size=10, latch=True)

    def callback(self, demo_msg):
        demo_msg.odom_path.header.frame_id = "map" # FIXME:
        self.odom_path_pub.publish(demo_msg.odom_path)
        self.demo_path_pub.publish(demo_msg.demo_path)

        for feature_vector in demo_msg.feature_values:
            pass
            #print feature_vector.wall_time

if __name__ == '__main__':
    dv = DemoViz()
    rospy.spin()

