#!/usr/bin/python

import sys
import rosbag
from tf.transformations import euler_from_quaternion

if __name__ == '__main__':

    if len(sys.argv) < 2:
        print "Usage: get_list_of_recoveries bag_file [output_file]"

    else:
        bag = rosbag.Bag(sys.argv[1])

        if len(sys.argv) == 3:
            output_file = open(sys.argv[2], 'w')

        for topic, msg, t in bag.read_messages(topics=['/recovery_supervisor/recovery_locations']):
            pose = msg.pose_stamped.pose
            quaternion = (pose.orientation.x, pose.orientation.y, pose.orientation.z, pose.orientation.w)
            line = str(msg.index) + " " +  str(pose.position.x) + " " +\
                    str(pose.position.y) + " " + str(euler_from_quaternion(quaternion)[2])
            if len(sys.argv) == 3:
                output_file.write(line + "\n")
            else:
                print line

        bag.close()

